/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeeficienciadealunos.forms;

import br.com.gestaodeeficienciadealunos.Mysql;
import br.com.gestaodeeficienciadealunos.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;


public class FormMain extends javax.swing.JFrame {

    Usuario usuario;

    /**
     * Creates new form NewJFrame
     */
    
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        GEA = new javax.swing.JMenu();
        cadastro = new javax.swing.JMenu();
        menu_algoritmo = new javax.swing.JMenuItem();
        menu_aluno = new javax.swing.JMenuItem();
        menu_area_pesquisa = new javax.swing.JMenuItem();
        menu_complexidade = new javax.swing.JMenuItem();
        menu_curso = new javax.swing.JMenuItem();
        menu_linguagem_programacao = new javax.swing.JMenuItem();
        menu_problema = new javax.swing.JMenuItem();
        menu_solucao = new javax.swing.JMenuItem();
        menu_usuario = new javax.swing.JMenu();
        ativar2FA = new javax.swing.JMenuItem();
        desativar2FA = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Eficiência de Alunos");
        setResizable(false);

        jMenuBar1.setName("menu_principal"); // NOI18N

        GEA.setText("Gestão de Eficiência de Alunos");

        cadastro.setText("Cadastro");

        menu_algoritmo.setText("Algoritmo");
        menu_algoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_algoritmoActionPerformed(evt);
            }
        });
        cadastro.add(menu_algoritmo);

        menu_aluno.setText("Aluno");
        menu_aluno.setToolTipText("");
        menu_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_alunoActionPerformed(evt);
            }
        });
        cadastro.add(menu_aluno);

        menu_area_pesquisa.setText("Área de pesquisa");
        menu_area_pesquisa.setToolTipText("");
        menu_area_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_area_pesquisaActionPerformed(evt);
            }
        });
        cadastro.add(menu_area_pesquisa);

        menu_complexidade.setText("Complexidade");
        menu_complexidade.setToolTipText("");
        menu_complexidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_complexidadeActionPerformed(evt);
            }
        });
        cadastro.add(menu_complexidade);

        menu_curso.setText("Curso");
        menu_curso.setToolTipText("");
        menu_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cursoActionPerformed(evt);
            }
        });
        cadastro.add(menu_curso);

        menu_linguagem_programacao.setText("Linguagem de programação");
        menu_linguagem_programacao.setToolTipText("");
        menu_linguagem_programacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_linguagem_programacaoActionPerformed(evt);
            }
        });
        cadastro.add(menu_linguagem_programacao);

        menu_problema.setText("Problema");
        menu_problema.setToolTipText("");
        menu_problema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_problemaActionPerformed(evt);
            }
        });
        cadastro.add(menu_problema);

        menu_solucao.setText("Solução");
        menu_solucao.setToolTipText("");
        menu_solucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_solucaoActionPerformed(evt);
            }
        });
        cadastro.add(menu_solucao);

        GEA.add(cadastro);

        menu_usuario.setText("Usuário");

        ativar2FA.setText("Ativar 2FA");
        ativar2FA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativar2FAActionPerformed(evt);
            }
        });
        menu_usuario.add(ativar2FA);

        desativar2FA.setText("Desativar 2FA");
        desativar2FA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desativar2FAActionPerformed(evt);
            }
        });
        menu_usuario.add(desativar2FA);

        GEA.add(menu_usuario);

        menu_sair.setText("Sair");
        menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sairActionPerformed(evt);
            }
        });
        GEA.add(menu_sair);

        jMenuBar1.add(GEA);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_alunoActionPerformed
        FormAluno aluno = new FormAluno(this);
        this.setEnabled(false);
        aluno.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menu_alunoActionPerformed

    private void menu_area_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_area_pesquisaActionPerformed
        FormAreaPesquisa area_pesquisa = new FormAreaPesquisa(this);
        this.setEnabled(false);
        area_pesquisa.setVisible(true);
    }//GEN-LAST:event_menu_area_pesquisaActionPerformed

    private void menu_complexidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_complexidadeActionPerformed
        FormComplexidade complexidade = new FormComplexidade(this);
        this.setEnabled(false);
        complexidade.setVisible(true);
    }//GEN-LAST:event_menu_complexidadeActionPerformed

    private void menu_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cursoActionPerformed
        FormCursos cursos = new FormCursos(this);
        this.setEnabled(false);
        cursos.setVisible(true);
    }//GEN-LAST:event_menu_cursoActionPerformed

    private void menu_linguagem_programacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_linguagem_programacaoActionPerformed
        FormLinguagens linguagens = new FormLinguagens(this);
        this.setEnabled(false);
        linguagens.setVisible(true);     
    }//GEN-LAST:event_menu_linguagem_programacaoActionPerformed

    private void menu_problemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_problemaActionPerformed
        FormProblemas problemas = new FormProblemas(this);
        this.setEnabled(false);
        problemas.setVisible(true);
    }//GEN-LAST:event_menu_problemaActionPerformed

    private void menu_solucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_solucaoActionPerformed
        FormSolucao solucao = new FormSolucao(this);
        this.setEnabled(false);
        solucao.setVisible(true);
    }//GEN-LAST:event_menu_solucaoActionPerformed

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_menu_sairActionPerformed

    private void menu_algoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_algoritmoActionPerformed
        FormAlgoritmo algoritmo = new FormAlgoritmo(this);
        this.setEnabled(false);
        algoritmo.setVisible(true);
    }//GEN-LAST:event_menu_algoritmoActionPerformed

    private void ativar2FAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativar2FAActionPerformed
        System.out.println("clicou em ativar");
        
        try{
            /* verifica se o usuario tem a 2FA ativada e mostra mensagem de erro caso esteja */
            Connection con = Mysql.conectar();
            PreparedStatement ps = con.prepareStatement("SELECT 2FA FROM usuario WHERE COD_USUARIO = ?");

            ps.setInt(1, usuario.idUsuario);

            ResultSet rs = ps.executeQuery();

            if(rs.next()){
                if(rs.getInt("2FA") == 0){
                    OkHttpClient client = new OkHttpClient();

                    Request request = new Request.Builder()
                        .url("https://www.authenticatorapi.com/pair.aspx?AppName=Gestao%20de%20Eficiencia%20de%20Alunos&AppInfo=" + usuario.nomeUsuario + "&SecretCode=GEA_2020_newton")
                        .build();

                    try (Response response = client.newCall(request).execute()) {
                        String html = "<html>" + response.body().string() + "</html>";
                        //System.out.println(html);

                        int confirmaQRCode = JOptionPane.showConfirmDialog(null, "Atenção! Escaneie o QR Code em seu app de autenticação preferido.\n\n"
                                 + "Ao clicar em OK, você estará ativando o 2FA,\ne só conseguirá fazer login utilizando o token no próximo acesso!\n\n"
                                 + "Caso queira fazer isto depois, clique em cancelar.\n\n"
                                 + html, "Ativar 2FA", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);

                        //System.out.println(confirmaQRCode);
                        if(confirmaQRCode == 0){
                            System.out.println("Confirmou: " + usuario.idUsuario);
                            try{
                                usuario.ativar2FA();
                                JOptionPane.showMessageDialog(this, "Autenticação em 2 fatores ativada com sucesso!");
                            }
                            catch(SQLException e)
                            {
                                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                            }
                        }
                        //else if(confirmaQRCode == 2){
                        //    System.out.println("Cancelou");
                        //}
                    }
                    catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Não foi possível gerar o QR Code, tente novamente!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Você já está utilizando a Autenticação em 2 fatores!", "2FA", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_ativar2FAActionPerformed

    private void desativar2FAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desativar2FAActionPerformed
        System.out.println("clicou em desativar");
        
        int confirmaQRCode = JOptionPane.showConfirmDialog(null, "Atenção! Ao desativar a Autenticação em 2 fatores, você corre riscos de perder seu acesso caso alguém roube sua senha!\n\n"
                     + "Ao clicar em OK, você estará desativando o 2FA, e voltará a fazer login utilizando somente usuário e senha no próximo acesso!\n\n"
                     + "Caso não queira desativar, clique em cancelar.\n\n", "Desativar 2FA", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
            
            //System.out.println(confirmaQRCode);
            if(confirmaQRCode == 0){
                System.out.println("Desativou" + usuario.idUsuario);
                try{
                    /* verifica se o usuario tem a 2FA desativada e mostra mensagem de erro caso esteja */
                    Connection con = Mysql.conectar();
                    PreparedStatement ps = con.prepareStatement("SELECT 2FA FROM usuario WHERE COD_USUARIO = ?");

                    ps.setInt(1, usuario.idUsuario);

                    ResultSet rs = ps.executeQuery();

                    if(rs.next()){
                        if(rs.getInt("2FA") == 1){
                            Usuario.desativar2FA();
                            JOptionPane.showMessageDialog(this, "Autenticação em 2 fatores desativada!");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Você não está utilizando a Autenticação em 2 fatores!", "2FA", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                }
            }
            //else if(confirmaQRCode == 2){
            //    System.out.println("Cancelou");
            //}
    }//GEN-LAST:event_desativar2FAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMain main_screen = new FormMain();
                main_screen.setVisible(true);
                main_screen.setEnabled(false);
                FormLogin login_screen = new FormLogin(main_screen);
                login_screen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GEA;
    private javax.swing.JMenuItem ativar2FA;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem desativar2FA;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_algoritmo;
    private javax.swing.JMenuItem menu_aluno;
    private javax.swing.JMenuItem menu_area_pesquisa;
    private javax.swing.JMenuItem menu_complexidade;
    private javax.swing.JMenuItem menu_curso;
    private javax.swing.JMenuItem menu_linguagem_programacao;
    private javax.swing.JMenuItem menu_problema;
    private javax.swing.JMenuItem menu_sair;
    private javax.swing.JMenuItem menu_solucao;
    private javax.swing.JMenu menu_usuario;
    // End of variables declaration//GEN-END:variables
}
